repos:

  # YAML
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:

      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.41.0
    hooks:

      - id: markdownlint
        args: [ "--fix" ]

  # Checkov
  - repo: https://github.com/bridgecrewio/checkov.git
    rev: 3.2.190
    hooks:
      - id: checkov
        files: .+
        verbose: false


  - repo: local
    hooks:

      - id: black
        name: black
        description: "Black: The uncompromising Python code formatter"
        entry: poetry run black
        language: system
        minimum_pre_commit_version: 2.9.2
        require_serial: true
        types_or: [ python, pyi ]


      - id: ruff
        name: ruff
        description: "Run 'ruff' for extremely fast Python linting"
        entry: poetry run ruff
        language: system
        types: [ python ]
        args: [ "check", "--fix" ]
        require_serial: false
        additional_dependencies: [ ]
        minimum_pre_commit_version: '0'
        files: '^(src|tests)/'


      - id: mypy
        name: mypy
        description: '`mypy` will check Python types for correctness'
        entry: poetry run mypy
        language: system
        types_or: [ python, pyi ]
        require_serial: true
        additional_dependencies: [ ]
        minimum_pre_commit_version: '2.9.2'
        files: '^(src|tests)/'


      - id: tealer
        name: tealer
        description: "Run AlgoKit `Tealer` for TEAL static analysis"
        entry: algokit
        language: system
        args: [project, run, "audit-teal"]
        require_serial: false
        additional_dependencies: []
        minimum_pre_commit_version: "0"
        files: '^.*\.teal$'
